import { ApiProperty } from '@nestjs/swagger';
import {
  type AssistAvailability,
  type ConsultationNote,
  type DraftRefusalReason,
  type ExtractionCandidate,
  type MedicalRecordEntry,
  type NoteDraft,
  type NoteDraftResult,
  type Prescription,
  type RecordSummary,
} from '@remedyo/shared';
import { AppointmentDto } from '../../appointments/dto/appointment.response';

/**
 * Response models for the medical records surface (design D7). Each class
 * `implements` the `@remedyo/shared` type it mirrors.
 *
 * Two of these are generated by the self-hosted model rather than authored by
 * a doctor — the note draft and the record summary — and both are labelled as
 * such, because a reader of the reference should not mistake model output for
 * the record.
 */

export class ConsultationNoteDto implements ConsultationNote {
  @ApiProperty({ format: 'uuid' })
  id!: string;

  @ApiProperty({ format: 'uuid' })
  appointmentId!: string;

  @ApiProperty()
  findings!: string;

  @ApiProperty()
  diagnosis!: string;

  @ApiProperty()
  recommendations!: string;

  @ApiProperty({ nullable: true })
  followUp!: string | null;

  @ApiProperty({ description: 'The doctor who signed the note.' })
  authorName!: string;

  @ApiProperty({ format: 'date-time' })
  createdAt!: string;

  @ApiProperty({ format: 'date-time', description: 'Notes are revised, never deleted.' })
  updatedAt!: string;
}

export class PrescriptionDto implements Prescription {
  @ApiProperty({ format: 'uuid' })
  id!: string;

  @ApiProperty({ format: 'uuid' })
  appointmentId!: string;

  @ApiProperty()
  medication!: string;

  @ApiProperty()
  dosage!: string;

  @ApiProperty()
  frequency!: string;

  @ApiProperty()
  durationDays!: number;

  @ApiProperty({ nullable: true })
  instructions!: string | null;

  @ApiProperty({ description: 'The doctor who issued it.' })
  prescriberName!: string;

  @ApiProperty({ format: 'date-time' })
  issuedAt!: string;
}

/**
 * A generated plain-language rendering of a signed note.
 *
 * Not the medical record: shown beside the clinical note, never instead of it,
 * and only while it still explains the note's current version.
 */
export class RecordSummaryDto implements RecordSummary {
  @ApiProperty()
  summary!: string;

  @ApiProperty({ description: 'The model that produced it, so what is on screen can be traced.' })
  model!: string;

  @ApiProperty({ format: 'date-time' })
  generatedAt!: string;
}

/** Prescription values read out of a doctor's own message. Never a prescription. */
export class ExtractionCandidateDto implements ExtractionCandidate {
  @ApiProperty()
  medication!: string;

  @ApiProperty()
  dosage!: string;

  @ApiProperty()
  frequency!: string;

  @ApiProperty()
  durationDays!: number;

  @ApiProperty({ nullable: true })
  instructions!: string | null;

  @ApiProperty({ format: 'uuid', description: 'The doctor message these values were read from.' })
  sourceMessageId!: string;

  @ApiProperty({ description: 'The words in that message the values came from.' })
  excerpt!: string;
}

/**
 * A generated note draft, for the doctor to edit and sign.
 *
 * Scaffolding, not the record: it pre-fills the form and nothing else. The
 * doctor's save through the note endpoint remains the only writer.
 */
export class NoteDraftDto implements NoteDraft {
  @ApiProperty()
  findings!: string;

  @ApiProperty()
  diagnosis!: string;

  @ApiProperty()
  recommendations!: string;

  @ApiProperty({ nullable: true })
  followUp!: string | null;

  @ApiProperty({
    type: [ExtractionCandidateDto],
    description: 'Verified prescription values, each traceable to the doctor’s own message.',
  })
  extractionCandidates!: ExtractionCandidateDto[];

  @ApiProperty()
  model!: string;

  @ApiProperty({ format: 'date-time' })
  generatedAt!: string;
}

/**
 * The two shapes generation can return.
 *
 * A refusal is an ordinary outcome rather than an error — a transcript that is
 * too thin to draft from is not a failure — so it is a 200 with a different
 * body, and the document says so with `oneOf`.
 */
export class DraftedNoteResultDto
  implements Extract<NoteDraftResult, { status: 'drafted' }>
{
  @ApiProperty({ enum: ['drafted'], example: 'drafted' })
  status!: 'drafted';

  @ApiProperty({ type: NoteDraftDto })
  draft!: NoteDraftDto;
}

export class RefusedNoteResultDto
  implements Extract<NoteDraftResult, { status: 'refused' }>
{
  @ApiProperty({ enum: ['refused'], example: 'refused' })
  status!: 'refused';

  @ApiProperty({
    enum: ['transcript-empty', 'transcript-too-thin', 'unavailable'],
    description:
      'Why no draft was produced. All three render as one absent-assistance state.',
  })
  reason!: DraftRefusalReason;
}

export class MedicalRecordEntryDto implements MedicalRecordEntry {
  @ApiProperty({ type: AppointmentDto })
  appointment!: AppointmentDto;

  @ApiProperty({ type: ConsultationNoteDto, nullable: true })
  note!: ConsultationNoteDto | null;

  @ApiProperty({ type: [PrescriptionDto] })
  prescriptions!: PrescriptionDto[];

  @ApiProperty({
    type: RecordSummaryDto,
    nullable: true,
    description: 'Null when generation is disabled, unavailable, or the summary is stale.',
  })
  summary!: RecordSummaryDto | null;
}

/** Whether assist surfaces should be offered at all. */
export class AssistAvailabilityDto implements AssistAvailability {
  @ApiProperty({ description: 'False when clinical assist is switched off for this deployment.' })
  enabled!: boolean;

  @ApiProperty({ nullable: true, description: 'The model that would answer, when enabled.' })
  model!: string | null;
}
